---
apiVersion: gateway.mulesoft.com/v1alpha1
kind: Extension
metadata:
  labels:
    title: combined-message-logging
    category: Custom
    description: Logs request and response headers of each call as one JSON entry
    metadata/interfaceScope: api,resource
spec:
  extends:
    - name: extension-definition
      namespace: default
  properties: {}
  required: []
